name: "Docbot Discord CI/CD"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php: ['8.0']
    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies & Setup App
        run: make install

      - name: Execute tests
        run: make test
